import { NextResponse, type NextRequest } from "next/server";
import { supabaseAuthClient } from "@/lib/auth/supabase";

/**
 * Sign-in landing. Two forms, both from Supabase:
 *  - `?code=…` : PKCE code from a magic link requested by this app;
 *  - `?token_hash=…&type=magiclink` : the SSR pattern for custom e-mail templates
 *    (`{{ .SiteURL }}/auth/callback?token_hash={{ .TokenHash }}&type=magiclink`) and for
 *    links generated by the admin API.
 * Either way the session lands in the cookie and the user is sent to `next`.
 */
export async function GET(req: NextRequest) {
  const url = new URL(req.url);
  const code = url.searchParams.get("code");
  const tokenHash = url.searchParams.get("token_hash");
  const type = url.searchParams.get("type") ?? "magiclink";
  const next = url.searchParams.get("next") ?? "/";
  const target = next.startsWith("/") && !next.startsWith("//") ? next : "/";
  const sb = await supabaseAuthClient();
  if (code) {
    const { error } = await sb.auth.exchangeCodeForSession(code);
    if (!error) return NextResponse.redirect(new URL(target, url.origin));
  } else if (tokenHash && (type === "magiclink" || type === "email" || type === "signup" || type === "recovery")) {
    const { error } = await sb.auth.verifyOtp({ token_hash: tokenHash, type });
    if (!error) return NextResponse.redirect(new URL(target, url.origin));
  }
  return NextResponse.redirect(new URL("/connexion?erreur=lien", url.origin));
}
