import { NextResponse, type NextRequest } from "next/server";
import { supabaseAuthClient } from "@/lib/auth/supabase";

/**
 * Sign-in landing. Three forms, all from Supabase:
 *  - `?code=…` : PKCE code from a magic link requested by this app in that flow;
 *  - `?token_hash=…&type=magiclink` : the SSR pattern for custom e-mail templates
 *    (`{{ .SiteURL }}/auth/callback?token_hash={{ .TokenHash }}&type=magiclink`) and for
 *    links generated by the admin API;
 *  - nothing in the query : the implicit-flow link the sign-in form requests, whose session
 *    sits in the URL's hash the server cannot see. A small page reads it and hands it to
 *    /auth/session, so the link works from any browser, the phone's mail app included.
 * Either way the session lands in the cookie and the user is sent to `next`.
 */
export async function GET(req: NextRequest) {
  const url = new URL(req.url);
  const code = url.searchParams.get("code");
  const tokenHash = url.searchParams.get("token_hash");
  const type = url.searchParams.get("type") ?? "magiclink";
  const next = url.searchParams.get("next") ?? "/";
  const target = next.startsWith("/") && !next.startsWith("//") ? next : "/";
  const sb = await supabaseAuthClient();
  if (code) {
    const { error } = await sb.auth.exchangeCodeForSession(code);
    if (!error) return NextResponse.redirect(new URL(target, url.origin));
  } else if (tokenHash && (type === "magiclink" || type === "email" || type === "signup" || type === "recovery")) {
    const { error } = await sb.auth.verifyOtp({ token_hash: tokenHash, type });
    if (!error) return NextResponse.redirect(new URL(target, url.origin));
  } else {
    return new NextResponse(hashPage(target), { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" } });
  }
  return NextResponse.redirect(new URL("/connexion?erreur=lien", url.origin));
}

/** The page that turns the hash into cookies: plain HTML, so it works before the app loads. */
function hashPage(next: string): string {
  const target = JSON.stringify(next);
  return [
    '<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Connexion · Guichet</title>',
    "<style>body{margin:0;min-height:100vh;display:grid;place-items:center;font-family:system-ui,sans-serif;background:#0b2545;color:#fff}p{font-size:15px}</style></head><body><p>Connexion…</p><script>",
    "(function(){",
    '  var h = new URLSearchParams(location.hash.replace(/^#/, ""));',
    '  var a = h.get("access_token"), r = h.get("refresh_token");',
    `  var next = ${target};`,
    '  if (!a || !r) { location.replace("/connexion?erreur=lien"); return; }',
    '  fetch("/auth/session", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ access_token: a, refresh_token: r }) })',
    '    .then(function (res) { location.replace(res.ok ? next : "/connexion?erreur=lien"); })',
    '    .catch(function () { location.replace("/connexion?erreur=lien"); });',
    "})();",
    "</script></body></html>",
  ].join("\n");
}
